import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { DefaultSession, getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import DarkMode from "./Darkmode";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session: DefaultSession | null = await getServerSession(authOptions);
  let res = cookies().get("mode");
  console.log(res?.value);
  return (
    <html lang="en">
      <body
        className={
          res !== undefined && res?.value === "dark" ? "dark-mode" : ""
        }
      >
        <div className="navbar">
          <Link href={`/`} className="logo">
            <div>AppleForum</div>
          </Link>
          <Link href={`/list`}>List</Link>
          {session === null ? (
            <LoginBtn></LoginBtn>
          ) : (
            <LogoutBtn userName={session.user?.name!}></LogoutBtn>
          )}
          <DarkMode></DarkMode>
        </div>
        {children}
      </body>
    </html>
  );
}
